/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Cpu.c
**     Project     : TX9BVA
**     Processor   : MC9S08PA4VTG
**     Component   : MC9S08PA4_16
**     Version     : Component 01.105, Driver 01.40, CPU db: 3.00.000
**     Datasheet   : MC9S08PA4RM Rev. 0 Draft B, 10/2011
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2015-03-16, 23:52, # CodeGen: 15
**     Abstract    :
**         This component "MC9S08PA4_16" contains initialization 
**         of the CPU and provides basic methods and events for 
**         CPU core settings.
**     Settings    :
**
**     Contents    :
**         EnableInt  - void Cpu_EnableInt(void);
**         DisableInt - void Cpu_DisableInt(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.40
** @brief
**         This component "MC9S08PA4_16" contains initialization 
**         of the CPU and provides basic methods and events for 
**         CPU core settings.
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

#pragma MESSAGE DISABLE C4002 /* WARNING C4002: Result not used is ignored */

#include "AD1.h"
#include "Backlight.h"
#include "Signal_In.h"
#include "Lever_Pos.h"
#include "PWM_In.h"
#include "PWM_Timer.h"
#include "WDT.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR register */
volatile byte CCR_lock;                /* Nesting level of critical regions */


/*
** ===================================================================
**     Method      :  Cpu_SWIInterrupt (component MC9S08PA4_16)
**
**     Description :
**         This ISR services the SWI interrupt.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_SWIInterrupt)
{
  Cpu_OnSwINT();                       /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  Cpu_Interrupt (component MC9S08PA4_16)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  //asm(BGND);
  return;
  /*lint -restore Enable MISRA rule (1.1) checking. */
}


/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S08PA4_16)
**     Description :
**         Disables maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S08PA4_16)
**     Description :
**         Enables maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S08PA4_16)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */

#pragma NO_FRAME
#pragma NO_EXIT
void _EntryPoint(void)
{
  /* ### MC9S08PA4_16 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* WDOG_CNT: CNT=0xC520 */
  setReg16(WDOG_CNT, 0xC520U);         /* First part of the WDG unlock sequence */ 
  /* WDOG_CNT: CNT=0xD928 */
  setReg16(WDOG_CNT, 0xD928U);         /* Second part of the WDG unlock sequence */ 
  /*  Initialization of Init_WDOG */
  /* WDOG_CS1: EN=0,INT=0,UPDATE=1,TST=0,DBG=0,WAIT=1,STOP=1 */
  setReg8(WDOG_CS1, 0x23U);             
  /* WDOG_CS2: WIN=0,FLG=0,??=0,PRES=0,??=0,??=0,CLK=1 */
  setReg8(WDOG_CS2, 0x01U);             
  /* WDOG_TOVAL: TOVAL=0x30 */
  setReg16(WDOG_TOVAL, 0x30U);          
  /* Common initialization of the write once registers */
  /* SYS_SOPT1: FTM0PS=0,BKGDPE=1,RSTPE=0,FWAKE=0,STOPE=0 */
  clrSetReg8Bits(SYS_SOPT1, 0x27U, 0x08U); 
  /* PMC_SPMSC1: LVWIE=0,LVDRE=1,LVDSE=1,LVDE=1,BGBDS=0,BGBE=1 */
  clrSetReg8Bits(PMC_SPMSC1, 0x22U, 0x1DU); 
  /* PMC_SPMSC2: LVDV=0,LVWV=0 */
  clrReg8Bits(PMC_SPMSC2, 0x70U);       
  /*  System clock initialization */
  /*lint -save  -e923 Disable MISRA rule (11.3) checking. */
  if (*(uint8_t*)0xFF6FU != 0xFFU) {   /* Test if the device trim value is stored on the specified address */
    ICS_C3 = *(uint8_t*)0xFF6FU;       /* Initialize ICS_C3 register from a non volatile memory */
    ICS_C4 = (uint8_t)((*(uint8_t*)0xFF6EU) & (uint8_t)0x01U); /* Initialize ICS_C4 register from a non volatile memory */
  }
  /*lint -restore Enable MISRA rule (11.3) checking. */
  /* ICS_C1: CLKS=0,RDIV=0,IREFS=1,IRCLKEN=1,IREFSTEN=0 */
  setReg8(ICS_C1, 0x06U);              /* Initialization of the ICS control register 1 */ 
  /* ICS_C2: BDIV=0,LP=0,??=0,??=0,??=0,??=0 */
  setReg8(ICS_C2, 0x00U);              /* Initialization of the ICS control register 2 */ 
  /* ICS_C4: LOLIE=0,CME=0 */
  clrReg8Bits(ICS_C4, 0xA0U);           

  /*** End of PE initialization code after reset ***/
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm   jmp _Startup ;               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S08PA4_16)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  #ifdef PEX_RTOS_INIT
    PEX_RTOS_INIT();                   /* Initialization of the selected RTOS. Macro is defined by the RTOS component. */
  #endif
  /* SCG_C1: ??=0,FTM1=1,FTM0=1,??=0,??=0,??=0,??=0,RTC=0 */
  setReg8(SCG_C1, 0x60U);               
  /* SCG_C2: ??=0,??=0,DBG=1,NVM=1,IPC=1,??=0,??=0,??=0 */
  setReg8(SCG_C2, 0x38U);               
  /* SCG_C3: ??=0,??=0,??=0,SCI0=1,??=0,??=0,??=0,??=0 */
  setReg8(SCG_C3, 0x10U);               
  /* SCG_C4: ACMP=1,??=0,ADC=1,??=0,IRQ=1,??=0,??=0,KBI0=1 */
  setReg8(SCG_C4, 0xA9U);               
  /* Common initialization of the CPU registers */
  /* ADC_APCTL1: ADPC3=1 */
  setReg8Bits(ADC_APCTL1, 0x08U);       
  /* PORT_PTAD: PTAD0=0 */
  clrReg8Bits(PORT_PTAD, 0x01U);        
  /* PORT_PTAPE: PTAPE1=0,PTAPE0=0 */
  clrReg8Bits(PORT_PTAPE, 0x03U);       
  /* PORT_PTAOE: PTAOE0=1 */
  setReg8Bits(PORT_PTAOE, 0x01U);       
  /* PORT_PTAIE: PTAIE1=1,PTAIE0=0 */
  clrSetReg8Bits(PORT_PTAIE, 0x01U, 0x02U); 
  /* PORT_PTBD: PTBD7=0,PTBD6=0,PTBD5=0,PTBD4=0,PTBD3=0 */
  clrReg8Bits(PORT_PTBD, 0xF8U);        
  /* PORT_PTBPE: PTBPE7=0,PTBPE6=0,PTBPE5=0,PTBPE4=0,PTBPE3=0,PTBPE2=0,PTBPE1=0,PTBPE0=0 */
  setReg8(PORT_PTBPE, 0x00U);           
  /* PORT_PTBOE: PTBOE7=1,PTBOE6=1,PTBOE5=1,PTBOE4=1,PTBOE3=1,PTBOE2=0,PTBOE1=0,PTBOE0=0 */
  setReg8(PORT_PTBOE, 0xF8U);           
  /* PORT_PTBIE: PTBIE7=0,PTBIE6=0,PTBIE5=0,PTBIE4=0,PTBIE3=0,PTBIE2=1,PTBIE1=1,PTBIE0=1 */
  setReg8(PORT_PTBIE, 0x07U);           
  /* IPC_ILRS9: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS9, 0x00U);            
  /* IPC_ILRS8: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS8, 0x00U);            
  /* IPC_ILRS7: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS7, 0x00U);            
  /* IPC_ILRS6: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS6, 0x00U);            
  /* IPC_ILRS5: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS5, 0x00U);            
  /* IPC_ILRS4: ILRn3=0,ILRn2=2,ILRn1=2,ILRn0=0 */
  setReg8(IPC_ILRS4, 0x28U);            
  /* IPC_ILRS3: ILRn3=0,ILRn2=0,ILRn1=1,ILRn0=0 */
  setReg8(IPC_ILRS3, 0x04U);            
  /* IPC_ILRS2: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS2, 0x00U);            
  /* IPC_ILRS1: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS1, 0x00U);            
  /* IPC_ILRS0: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS0, 0x00U);            
  /* IPC_SC: IPCE=1,??=0,PSE=0,PSF=0,PULIPM=0,??=0,IPM=0 */
  setReg8(IPC_SC, 0x80U);               
      /* Initialization of the PORT module */
  /* PORT_FCLKDIV: FLTDIV3=0,FLTDIV2=0,FLTDIV1=0 */
  setReg8(PORT_FCLKDIV, 0x00U);         
  /* PORT_IOFLT0: FLTC=0,FLTB=0,FLTA=0 */
  clrReg8Bits(PORT_IOFLT0, 0x3FU);      
  /* PORT_IOFLT2: FLTKBI0=0,FLTRST=0 */
  clrReg8Bits(PORT_IOFLT2, 0x0FU);      
  /* ### Shared modules init code ... */
  /* ###  "AD1" init code ... */
  AD1_Init();
  /* ### BitIO "Backlight" init code ... */
  /* ### BitsIO "Signal_In" init code ... */
  /* ### BitsIO "Lever_Pos" init code ... */
  /* ### Timer capture encapsulation "PWM_In" init code ... */
  PWM_In_Init();
  /* ### TimerInt "PWM_Timer" init code ... */
  PWM_Timer_Init();
  /* ###  WatchDog "WDT" init code ... */
  WDT_Init();
  /* WDOG_CNT: CNT=0xA602 */
  setReg16(WDOG_CNT, 0xA602U);          
  /* WDOG_CNT: CNT=0xB480 */
  setReg16(WDOG_CNT, 0xB480U);          
  CCR_lock = (byte)0;
  __EI();                              /* Enable interrupts */
  /* FTM0_SC: TOF=0 */
  clrReg8Bits(FTM0_SC, 0x80U);         /* Reset overflow interrupt request flag */ 
  /* FTM0_SC: TOIE=1 */
  setReg8Bits(FTM0_SC, 0x40U);         /* Enable overflow interrupt */ 
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/* NV_FPROT: FPOPEN=0,??=1,FPHDIS=1,FPHS=3,??=1,??=1,??=1 */
static const uint8_t NV_FPROT_INIT @0x0000FF7CU = 0x7FU;
/* NV_FSEC: KEYEN=1,??=1,??=1,??=1,??=1,SEC=2 */
static const uint8_t NV_FSEC_INIT @0x0000FF7FU = 0x7EU;
/*lint -restore Enable MISRA rule (1.1) checking. */

/* END Cpu. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
